---
- name: Install app apt dependencies
  become: true
  apt: name={{item}} state=installed
  with_items:
    - libgeos-dev

- name: Install python dependencies
  become: true
  apt: name={{item}} state=installed
  with_items:
    - build-essential
    - checkinstall
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev

- name: Extract python
  become: true
  unarchive:
    src: "https://www.python.org/ftp/python/{{python_version}}/Python-{{python_version}}.tgz"
    dest: /opt/
    remote_src: true
  args:
    creates: "/opt/Python-{{python_version}}/configure"

- name: Install python
  become: true
  shell: |
    cd /opt/Python-{{python_version}}
    ./configure
    sudo make
    sudo make altinstall 
  args:
    chdir: "/opt/Python-{{python_version}}"
    creates: "/usr/local/bin/python3.7"

- name: Create virtualenv
  become: yes
  become_user: '{{ app_user.username }}'
  command: python3.7 -m venv {{ venv_directory }}
  args:
    creates: "{{ venv_directory }}"

- name: Install requirements
  become: yes
  become_user: '{{ app_user.username }}'
  pip: 
    requirements: "{{ src_directory }}/requirements.txt"
    virtualenv: "{{ venv_directory }}"
