# Generated by Django 2.1.1 on 2018-11-20 16:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('iata', models.CharField(max_length=3)),
                ('icao', models.CharField(max_length=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326)),
                ('dst', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=200)),
                ('facility_type', models.CharField(max_length=200)),
            ],
        ),
    ]
