# Generated by Django 2.1.1 on 2018-11-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181120_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iata', models.CharField(max_length=3)),
                ('icao', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_id', models.CharField(max_length=200)),
                ('stops', models.IntegerField()),
                ('codeshare', models.BooleanField()),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_routes', to='core.Airport')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.Equipment')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_routes', to='core.Airport')),
            ],
        ),
    ]
