# Generated by Django 2.1.1 on 2018-11-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipment_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('iata', models.CharField(max_length=3)),
                ('icao', models.CharField(max_length=4)),
                ('callsign', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='airline_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.Airline'),
        ),
    ]
