# Generated by Django 2.1.1 on 2018-11-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181120_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='icao',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='iata',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='icao',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
