# Generated by Django 2.1.1 on 2018-11-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_airline_openflights_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='airline_id',
            new_name='airline',
        ),
    ]
