# Generated by Django 2.1.1 on 2018-11-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181120_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_routes', to='core.Airport'),
        ),
        migrations.AlterField(
            model_name='route',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.Equipment'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_routes', to='core.Airport'),
        ),
    ]
