# Generated by Django 2.1.1 on 2018-11-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181120_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes_as_dest', to='core.Airport'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes_as_source', to='core.Airport'),
        ),
    ]
