# Generated by Django 2.1.1 on 2018-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181122_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='degree',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='evcent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='pagerank',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
