# Generated by Django 2.1.1 on 2018-12-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181122_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='betweenness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='closeness',
            field=models.FloatField(null=True),
        ),
    ]
